title: Cambia la forma de pedalear..
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.8369176
  brandStrength: 0
  lightness: 0.7437276
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  rhythmicContrast: 0.7419355
typography_spectrum: 0.08064516
description: www.icedot.cl
navigation:
  - name: r
    id: 82af8e51-0441-43f0-a306-14f208d4771c
    type: content
layout_spectrum: 0.9874552
name: Icedot
