typography_spectrum: 0.1768973
color:
  saturation: 0.4122787
  lightness: 0.2243836
  brandStrength: 0.4867466
  rhythmicContrast: 0.04765236
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
layout_spectrum: 0.05172227
name: Icedot
navigation:
  - name: r
    id: 82af8e51-0441-43f0-a306-14f208d4771c
    type: content
title: Cambia la forma de pedalear..
description: www.icedot.cl
